### ISSUE TITLE
UI buttons are cut off

### ISSUE THREAD

**Issue by CarThax08** [awesomelewis2007/QuickRun#7]
When I open quick run (IDE or through the EXE) the buttons are cut off on the right side. For example, instead of saying CMD it just says CM. An image is attached. I'm going to try and fix it and create a pull request, I just wanted the issue documented.

![image](https://user-images.githubusercontent.com/30299999/151038990-1b76be40-9c75-47b8-acb1-95149fb5e01f.png)

**Comment by awesomelewis2007** [comment]
i think this is because of screen resolutions

**Comment by awesomelewis2007** [comment]
what's your resolution

**Comment by CarThax08** [comment]
I don't think it's a resolution issue though, as it happens in the forms editor too

**Comment by CarThax08** [comment]
I'm looking into it a bit.

**Comment by awesomelewis2007** [comment]
ill send you a binary of 0.1.17

**Comment by CarThax08** [comment]
Yeah, I just downloaded the latest release and it was still doing it. I recommend creating a new release for that

**Comment by CarThax08** [comment]
That fixed it.

**Comment by awesomelewis2007** [comment]
[Quickrun 0.1.17.zip](https://github.com/awesomelewis2007/QuickRun/files/7936354/Quickrun.0.1.17.zip)

**Comment by awesomelewis2007** [comment]
try that

**Comment by CarThax08** [comment]
I download the source and ran it in IDE. It worked fine

**Comment by CarThax08** [comment]
also, there's nothing in that zip

**Comment by awesomelewis2007** [comment]
> also, there's nothing in that zip

lmao made a zip but forgot to put the exe in

**Comment by awesomelewis2007** [comment]
> I download the source and ran it in IDE. It worked fine

ok thanks for the issue tho
